name: Continuous Integration-Continuous Deployment

on:
  push:
    branches:
      - main  

jobs:
 build:
    runs-on: ubuntu-24.04
    name: Continuous Integration
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: platformht/backend-image:latest

 deploy:
    runs-on: ubuntu-24.04
    name: Continuous Deployment
    needs: [build]
    steps:
      - name: Deploy to VPS using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /srv/backend/
            docker stop backend-image
            docker rm backend-image
            docker pull platformht/backend-image:latest
            docker-compose up -d
